/**
 * Built-in lists. Keys are the labels shown to users (and used as playlist names); values are
 * extra raw tags that map to them. The label itself always matches, so aliases list only other
 * spellings. Matching is on normalized text (see normalizeTag), so case, hyphens, "&" vs "and"
 * do not matter.
 *
 * - `families`: broad genres, used only when a track has no subgenre.
 * - `subgenres`: detailed genres; Discogs styles are the main source.
 * - `moods`: from Last.fm track tags.
 *
 * Users can override any section with ~/.config/sortify/tag_map.yaml (same shape).
 */
export interface TagMap {
  families: Record<string, string[]>;
  subgenres: Record<string, string[]>;
  moods: Record<string, string[]>;
}

export const DEFAULT_TAG_MAP: TagMap = {
  families: {
    // Also YouTube topic labels ("Pop music") and iTunes store genres ("Hip-Hop/Rap").
    Pop: ["pop music"],
    Rock: ["rock music"],
    Metal: [],
    Electronic: ["electronica", "edm", "dance", "electronic dance music", "electronic music"],
    "Hip Hop": ["hip-hop", "hiphop", "rap", "hip hop music", "hip-hop/rap"],
    "R&B and Soul": [
      "r&b",
      "rnb",
      "rhythm and blues",
      "soul",
      "funk / soul",
      "soul music",
      "r&b/soul",
    ],
    Jazz: [],
    Blues: [],
    Country: ["country music"],
    Folk: ["folk, world, & country"],
    Classical: ["classical music"],
    Latin: ["latin music", "music of latin america"],
    Reggae: [],
    Soundtrack: ["stage & screen", "score", "film score", "ost", "original soundtrack"],
    World: ["world music"],
    Indian: ["indian music", "music of india", "regional indian"],
    "Asian Music": ["music of asia"],
  },
  subgenres: {
    // Pop
    "Synth-pop": ["synthpop", "synth pop"],
    Electropop: [],
    "Dance-pop": [],
    "Indie Pop": [],
    "Dream Pop": [],
    "Art Pop": [],
    "Bedroom Pop": [],
    Hyperpop: [],
    "K-Pop": ["kpop", "korean pop"],
    "J-Pop": ["jpop", "japanese pop"],
    "Latin Pop": [],
    "Power Pop": [],
    Europop: ["euro pop"],
    "Teen Pop": [],
    // Rock
    "Alternative Rock": ["alternative", "alt rock", "alt-rock"],
    "Indie Rock": ["indie"],
    "Classic Rock": [],
    "Hard Rock": [],
    Punk: ["punk rock"],
    "Pop Punk": [],
    "Post-Punk": [],
    Emo: [],
    Grunge: [],
    Shoegaze: [],
    "Psychedelic Rock": ["psych rock", "psychedelic"],
    "Progressive Rock": ["prog rock", "prog"],
    "Post-Rock": [],
    "Math Rock": [],
    "Garage Rock": [],
    "Soft Rock": [],
    "Folk Rock": [],
    "Blues Rock": [],
    Britpop: [],
    "Surf Rock": ["surf"],
    // Metal
    "Heavy Metal": [],
    "Thrash Metal": ["thrash"],
    "Death Metal": [],
    "Black Metal": [],
    "Doom Metal": ["doom"],
    Metalcore: [],
    "Nu Metal": [],
    "Progressive Metal": ["prog metal"],
    "Power Metal": [],
    Djent: [],
    // Electronic
    House: [],
    "Deep House": [],
    "Tech House": [],
    "Progressive House": [],
    "Electro House": [],
    Techno: [],
    Trance: [],
    Psytrance: ["psy-trance", "psychedelic trance", "goa trance"],
    "Drum and Bass": ["drum n bass", "dnb", "d&b"],
    Jungle: [],
    Dubstep: [],
    "Future Bass": [],
    "UK Garage": ["2-step", "speed garage"],
    Breakbeat: ["breaks"],
    Hardstyle: [],
    "Big Room": [],
    Synthwave: ["retrowave", "outrun"],
    Vaporwave: [],
    Chillwave: [],
    Ambient: [],
    Downtempo: [],
    "Trip Hop": [],
    IDM: ["intelligent dance music"],
    Electro: [],
    "Electro Swing": [],
    Eurodance: [],
    "Italo-Disco": [],
    "Nu-Disco": [],
    Disco: [],
    "Lo-fi": ["lofi", "lo-fi hip hop", "lofi hip hop", "chillhop"],
    // Hip hop
    Trap: [],
    Drill: ["uk drill"],
    "Boom Bap": [],
    "Conscious Hip Hop": ["conscious"],
    "Gangsta Rap": ["gangsta"],
    "G-Funk": [],
    "Cloud Rap": [],
    "Emo Rap": [],
    "Pop Rap": [],
    "Alternative Hip Hop": ["alternative rap"],
    "Jazz Rap": ["jazz hop", "jazzy hip hop"],
    Grime: [],
    Phonk: [],
    // R&B, soul, funk
    "Contemporary R&B": [],
    "Alternative R&B": ["alt r&b", "pbr&b"],
    "Neo Soul": [],
    Funk: [],
    Motown: [],
    Gospel: [],
    "New Jack Swing": [],
    // Jazz
    "Smooth Jazz": [],
    Bebop: [],
    "Cool Jazz": [],
    "Jazz Fusion": ["fusion"],
    "Acid Jazz": [],
    Swing: [],
    "Bossa Nova": [],
    "Nu Jazz": [],
    // Country and folk
    Americana: [],
    Bluegrass: [],
    "Country Pop": [],
    "Outlaw Country": [],
    "Indie Folk": [],
    "Folk Pop": [],
    "Singer-Songwriter": [],
    // Latin
    Reggaeton: [],
    "Latin Trap": [],
    Bachata: [],
    Salsa: [],
    Cumbia: [],
    "Regional Mexican": ["corridos", "corridos tumbados"],
    // Reggae
    "Roots Reggae": [],
    Dancehall: [],
    Dub: [],
    Ska: [],
    // Other
    Afrobeats: ["afropop", "afro pop"],
    Afrobeat: [],
    Amapiano: [],
    // Indian (names used by Spotify, iTunes, Last.fm and YouTube)
    "Punjabi Pop": ["punjabi", "punjabi music"],
    Bhangra: ["modern bhangra"],
    "Desi Hip Hop": ["desi rap", "desi trap", "punjabi hip hop", "indian hip hop", "hindi hip hop"],
    "Indian Pop": ["hindi pop", "desi pop", "indipop", "indi pop"],
    Bollywood: ["filmi", "modern bollywood", "hindi film", "hindi film music"],
    Haryanvi: ["haryanvi pop", "haryanvi hip hop"],
    Sufi: ["qawwali", "ghazal", "ghazals"],
    "Indian Classical": ["hindustani classical", "hindustani", "carnatic"],
    "Indian Indie": ["desi indie", "hindi indie"],
    Devotional: ["devotional & spiritual", "bhajan", "bhakti"],
    Tamil: ["kollywood", "tamil pop"],
    Telugu: ["tollywood", "telugu pop"],
    "Video Game Music": ["video game", "vgm", "game soundtrack", "video game soundtrack"],
    Anime: ["anisong", "anime soundtrack"],
    "Modern Classical": ["neoclassical", "neo-classical", "contemporary classical"],
  },
  moods: {
    Chill: [
      "chillout",
      "chill out",
      "chilled",
      "relaxing",
      "relax",
      "calm",
      "mellow",
      "laid back",
      "soothing",
      "peaceful",
    ],
    Happy: [
      "feel good",
      "feelgood",
      "uplifting",
      "cheerful",
      "fun",
      "joyful",
      "positive",
      "happy songs",
    ],
    Sad: [
      "melancholy",
      "melancholic",
      "depressing",
      "heartbreak",
      "heartbroken",
      "sad songs",
      "emotional",
      "tearjerker",
      "crying",
    ],
    Energetic: [
      "energy",
      "upbeat",
      "workout",
      "gym",
      "running",
      "party",
      "hype",
      "pump up",
      "high energy",
      "driving",
    ],
    Romantic: ["love", "romance", "love songs", "love song", "sexy", "sensual"],
    Dark: ["ominous", "haunting", "sinister", "creepy", "eerie", "brooding"],
    Angry: ["aggressive", "rage", "anger"],
    Dreamy: ["ethereal", "atmospheric", "hypnotic", "trippy"],
    Nostalgic: ["nostalgia", "memories", "throwback"],
    Focus: ["study", "studying", "concentration", "study music", "work music", "coding"],
    Epic: ["powerful", "anthemic", "cinematic"],
  },
};
